Notes client updates
HCL-TECH-SOFTWARE/domino-keep-docs pull request #37
Opened 2021-09-13 18:17 UTC by Stwissel

## Change description

- Clarification on client scope
- Securing management and metrics endpoints

## Due diligence

- [X] tested locally using `bundle exec jekyll serve`

## Review/Merge

- [x] Ready for review
- [x] Ready for merge

2021-09-14 00:18 UTC, tanya-anurag requested changes

2021-09-14 00:18 UTC, tanya-anurag commented on docs/installconfig/configuration/notesclient.md
> +The HCL Domino REST API is designed for use with the HCL Domino server. The ability to deploy it to a Notes client on Windows or macOS is provided for ypur convenience to enable you to evaluate and e
Please change to -

The ability to deploy it to a Notes client on Windows or macOS is provided for your convenience- to enable you to evaluate and experiment. You can explore the API without setting up a HCL Domino server.

2021-09-14 00:18 UTC, tanya-anurag commented on docs/installconfig/configuration/security/securingKEEPEndpoints.md
> +- The metrics endpoint (8890) uses BASIC authentication with the user name set in the configuration variable `metrics/metricsUser` and the salted and encrypted password in the configuration variable
Please change to-

The metrics endpoint (8890) uses BASIC authentication with the user name set in the configuration variable `metrics/metricsUser` and the salted and encrypted password in the configuration variable `metrics/metricsPassword`. It is strongly recommended to update these values and only share with the metrics owner. The metrics endpoint is read only.

2021-09-14 14:30 UTC, Stwissel commented
@tanya-anurag  - updated as requested

2021-09-15 03:07 UTC, tanya-anurag approved these changes

2021-09-15 03:07 UTC, merged